# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(max_length=5),
        ),
    ]
